### ISSUE TITLE
Consider support for Dotty

### ISSUE THREAD

**Issue by sksamuel** [scapegoat-scala/scapegoat#391]

**Comment by mwz** [comment]
Perhaps TASTy inspection is something we should consider for Dotty support.
https://dotty.epfl.ch/docs/reference/metaprogramming/tasty-inspect.html

**Comment by sksamuel** [comment]
That's interesting. The question is, if you work that tasty level do you still have access to the original source as is (does tasty compile some things away), and does it have the original line numbers and so on.

**Comment by mwz** [comment]
It looks like you do get all of that - tasty files include information about types, source positions and also any scaladoc documentation that was included, which is pretty cool. I'm currently playing around with the reflection and it looks quite good. At first sight, the API is actually quite similar to the internal scala compiler's API.

**Comment by sksamuel** [comment]
It would need to have a mapping back to the original source, in other
words, it can't do any re-writing, otherwise we can't report on users code
as it was actually written.

**Comment by mwz** [comment]
> It would need to have a mapping back to the original source

Yes, it appears that you can extract the original source code from the `Position` object of the `Tree` by calling `tree.pos.sourceCode`, so e.g. if you keep track of the tree for the current line while traversing the tree, by calling `tree.pos.sourceCode` you'll get the original source code for that line, which is pretty neat.

**Comment by sksamuel** [comment]
That's really nice.

My alternative idea was to write a simple parser for the source code (not a
type checker). The advantages are we could run it as a bot on github as it
could work on a single file at a time. The disadvantage is that you
wouldn't have the full type checking.

**Comment by mwz** [comment]
Yeah, the obvious downside of using tasty files is that it requires the project to be compiled beforehand.

I'd discourage you from writing a custom parser because it's quite a lot of work and instead I'd probably consider using scalameta, which now has partial Dotty support.

**Comment by sksamuel** [comment]
Actually writing a parser like I had in mind is easy - a purely syntactic
parser. I've done it before for Java and SQL (admittedly Scala3 will
probably be more complicated than those).

The upsides are that a file can be parsed in isolation, so you can run it
against a code base in a fraction of the time of a real compiler. So it's
great for things like github actions.
The downsides are obvious - you can't do anything that requires context
from other files (eg, class.a == class.b requires context of class to know
a and b's types). So it's somewhat restrictive.

I don't know if something that works very quickly at the file level is a
useful tool or not. A lot of intellij's inspections are like this (the
intellij plugin I write has some local inspections).

Given that scalameta is the place to add inspections based on a full
compile, does that mean Scapegoat has no place in a Scala3 landscape, or
does it have a place anyway, or does it have a place as the file level
inspector.

What do you think?

**Comment by mwz** [comment]
I've been thinking about it recently and there are a few ways in which this can be approached:

1. Scalameta has been adding parsing support for Dotty ([https://github.com/scalameta/scalameta/issues/2022](https://github.com/scalameta/scalameta/issues/2022)), so once that's complete it will be a much better option than writing a custom parser. I think Scalastyle proved the value of syntactic checks and also this is the most lightweight linting you can do (without having to compile the code), so there will definitely be a room for this kind of checks in Scala 3.
2. It looks like Dotty compiler has a stage which extracts info into semanticdb files, so both aspects put together (via Scalafix) give you syntactic and semantic APIs on top of which you can build checks. Scalafix currently has a very limited number of available checks compared to Scapegoat, Wartremover and Scalastyle and also doesn't have the mechanism to generate an external report or expose issues via an API that could be used by external tools. Scalafix is getting integrated into Metals, so at some point, any of those checks could be potentially run in the IDE and also provide automatic rewrites to fix any issues, but I'm not so convinced that it is the best fit for a standalone tool that can be run as e.g. a PR check.
3. TASTy files are another option which I'm personally leaning towards. They give you a low-level API which looks very similar to the internal compiler API that Scapegoat uses, but obviously with a key advantage that it's not tied to the compiler and it's based around a stable interchange format. Using it does require the project to be initially compiled just like in the case of Scalafix (which needs to create the semanticdb), but I don't think that's a problem because you can just run it after the compilation step. The good think about this approach is that it doesn't couple you with the whole Scalameta/Scalafix stack and gives you the low-level API to implement complex checks.
4. You could probably also combine 3. with using Scalameta for any lightweight syntactic checks, but I'm not sure if there's any benefit in doing that except for maybe being able to execute it before the compilation as a Github App instead of a Github Action, but you'd probably want to compile your project and execute tests as a part of PR checks so that probably doesn't give you much benefit over 3.

**Comment by sksamuel** [comment]
So 3 seems like a good bet then.
